# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    ../../sys/server.nix
    ./hardware.nix
  ];

  networking.hostName = "router";

  skogsbrus = {
    fwupd.enable = true;
    grafana.enable = true;

    nix = {
      allowUnfree = true;
      flakes = true;
      gc = true;
      gc_schedule = "daily";
    };

    router = {
      enable = true;
      private_subnet = "10.77.77";
      guest_subnet = "10.88.88";
    };

    ssh.enable = true;
    sound.enable = false;

    tmux = {
      enable = true;
      bg_color = "red";
    };

    users = {
      # TODO: parameterize user names etc
    };

    wireguard = {
      enable = true;
      server = true;
      port = 666;
      subnet = "10.66.66";
      server_subnet = "10.77.77";
      unique_id = 1;
    };
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It‘s perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "21.11"; # Did you read the comment?
}
